name: Update Readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install -r requirements.txt || echo "No dependencies needed"

      - name: Run LeetCode Stats Script
        run: python update_readme.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Updated LeetCode stats in README" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/llEraserheadl1/LeetcodeSol.git
